### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by movitto**

### CODE REVIEW

**Comment by movitto** [comment]
@roliveri please review

**Comment by movitto** [comment]
@roliveri updated this in accordance to suggestions. Incorporated existing iso9660 classes in repo before refactoring to adapt to virtfs interface. Hopefully a bit simpler to see what's going on

**Comment by roliveri** [comment]
@movitto Didn't I say that the actual changes to the code should be made in a separate pull request?

**Comment by movitto** [comment]
@roliveri PR's 2-9 opened & need reviews

**Pull request closed without merging**
